### ISSUE TITLE
[Suggestion/ Interest Check] Tap To Cancel functionality

### ISSUE THREAD

**Issue by AnthonyMDev** [matej/MBProgressHUD#59]
Would a pull request for a simple to use tap to cancel addition be accepted? I've done this in a project I'm working on, and I think I could pretty easily implement this on the main class or as a category.

Would you be open to a pull request for this?

I know that you have offered users a way to set this up in #41 and #46. I'm basically using this method, but this would make it easier for others in the future.

**Comment by matej** [comment]
The HUD now comes with a button that can be used to cancel a task. See the demo for an example.
