### ISSUE TITLE
Using stop animation for navigation controller

### ISSUE THREAD

**Issue by thiagovargas** [matej/MBProgressHUD#63]
I've used this control on my app, but i got a strange situation. When user tap the cell, the app access a web service and then, navigate to another view controller (push). When user tap on back button, sometimes, instead of go back to previous viewcontroller animated, the screen blinks and go back.
So, i removed the MBProgressHUD and this nos occurs again.

What i'm doing wrong?

**Comment by matej** [comment]
That is a bit too broad to identify any sort of problem with MBProgressHUD. You'll have to provide code / a sample project too see what's going on. Try adding it to a different `view` or `view.window` instead.

**Comment by thiagovargas** [comment]
Can you see the project sample that i did? Can you run?
https://github.com/thiagovargas/sampleProgress

Thanks

**Comment by matej** [comment]
Closing this old issues. If this is still a problem by any chance you might want to take a look at the latest version and open a new issue.
