### ISSUE TITLE
when i use xcode8.0 runing ios8.4 app crash

### ISSUE THREAD

**Issue by LiYuLong012** [matej/MBProgressHUD#82]
# if __IPHONE_OS_VERSION_MIN_REQUIRED < 90000

```
    appearance = [UIActivityIndicatorView appearanceWhenContainedIn:[MBProgressHUD class], nil];
```
# else

```
    // For iOS 9+
    appearance = [UIActivityIndicatorView appearanceWhenContainedInInstancesOfClasses:@[[MBProgressHUD class]]];
```
# endif

this code get the iphoneos version gte 900000,  is 90300 so is go for ios 9+ .
then app crash .

why min required version is 90000

**Comment by matej** [comment]
You need to double check your iOS Deployment Target. Make sure it's iOS 8.4 or lower. This sounds like MBProgressHUD itself was built with a higher deployment target than your app.
