### ISSUE TITLE
About MBProgressHUD problem

### ISSUE THREAD

**Issue by ACommonChinese** [matej/MBProgressHUD#85]
Hi, In the stackoverflow, i searched a problem: http://stackoverflow.com/questions/25602009/mbprogresshud-resets-positions-of-uiviews-during-loading

And I did run into a problem something like that. ie, in the controller's view, there is a scroll view, if the scroll view is scrolling, and the MBProgressHUD appear, the position of MBProgressHUD will change compare with previous MBProgressHUD. I think may be it is because the controller's view resets to original position while scroll view is scrolling?

Thanks.

**Comment by matej** [comment]
I'm having a hard time understanding what the issue here is. If you don't want the HUD to scroll, do not add it to the scroll view, add to a parent view that is fixed, or to the Window if there is no other appropriate view.
